### ISSUE TITLE
I want to know how to use this package on my baxter research robot.

### ISSUE THREAD

**Issue by ghost** [h2r/ros_reality_bridge#7]
Hello, 

I am a beginner.

I want to use this package on my baxter research robot.
My baxter has a right electric gripper but does not have a left electric gripper (Instead left vacuum gripper).
 
In order to use this package, what should I do?

**Comment by ericrosenbrown** [comment]
In order to use this package with your adjusted gripper:

1) You'll need to change the launch file (https://github.com/h2r/ros_reality_bridge/blob/master/launch/ros_reality_bridge.launch) to not use the electric gripper on the left arm. Specifically, you'll need to change line 15 to use the urdf fragment of whatever the vacuum gripper is. If you don't have a urdf for the left vacuum gripper, just delete this line.
2) If you do have the urdf, and want the vacuum to appear in Unity, then you'll need to put that urdf into your unity project (https://github.com/h2r/ros_reality_legacy/tree/master/Assets/Resources/URDFs/Baxter), add the mesh files to that same folder with the same path that the URDF uses to reference the vacuum grippers, and then just change the RobotFactory gameobject to have it's path set to your new URDF. This will let you visualize the robot with it's vacuum gripper in unity.

Like I said, if you don't care about visualizing the vacuum gripper, just delete the left gripper line. Otherwise, you can do the steps above. 

If you have any issues or questions about getting this set up, please feel free to ask any clarifying questions! Thanks for using ROS Reality! :)

**Comment by ghost** [comment]
Thanks to your advice, I could run ros_reality_bridge.launch without problems!
I appreciate you.
